In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.io as pio
pio.renderers.default='notebook'
from ipywidgets import interact,IntSlider
pd.set_option('display.max_columns', None)

In [3]:
d = pd.read_excel("/Users/xaviijordi/Downloads/extraccio xavi2.xlsx")

In [4]:
d

,IdPersona,NombreCompleto,Sexo,Edad,Poblacion,Provincia,CodigoPostal,DireccionCompleta,TipoAbono,Categoria,FechaAltaAbono,FechaBajaAbono,SemanaAlta,SemanaBaja,MAlta,Mbaja,ReAlta,EsAbonado
0,4,", VENDES DIVERSES",Mujer,224,INDEFINIDA,0,Indef,"Indefinido INDEFINIDA, 23 2º 1ª",VINTRO COMPLERT,02 - ADULT,03/10/2023,24/10/2023,41,44,10,10,Si,No
1,4,", VENDES DIVERSES",Mujer,224,INDEFINIDA,0,Indef,"Indefinido INDEFINIDA, 23 2º 1ª",VINTRO COMPLERT,02 - ADULT,16/12/2023,19/12/2023,51,52,12,12,Si,No
2,4,", VENDES DIVERSES",Mujer,224,INDEFINIDA,0,Indef,"Indefinido INDEFINIDA, 23 2º 1ª",VINTRO COMPLERT,03 - GENT GRAN,02/11/2023,02/11/2023,45,45,11,11,Si,No
3,4,", VENDES DIVERSES",Mujer,224,INDEFINIDA,0,Indef,"Indefinido INDEFINIDA, 23 2º 1ª",VINTRO MIGDIA+CAP DE SETMANA,02 - ADULT,25/07/2023,25/07/2023,31,31,7,7,Si,No
4,4,", VENDES DIVERSES",Mujer,224,INDEFINIDA,0,Indef,"Indefinido INDEFINIDA, 23 2º 1ª",VERNEDA COMPLERT,02 - ADULT,24/09/2022,24/09/2022,39,39,9,9,Si,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,421511,"VERGARA LUNA, VALENTINA",Mujer,25,BARCELONA,BARCELONA,08026,"AVDA MERIDIANA, 107 1º1ª",VINTRO MATINS,02 - ADULT,28/06/2022,01/12/2022,27,49,6,12,No,Sí
8132,421512,"RICART GARCIA, CARLOS",Hombre,48,(nulo),(nulo),(nulo),",",ONLINE VERNEDA,02 - ADULT,02/12/2023,09/12/2023,49,50,12,12,No,No
8133,421611,"TOUCEDA ELIZALDE, DANIEL",Hombre,21,B ARCELONA,NaN,08020,"RAMBLA GUIPUSCOA, 131-2ºe",VERNEDA JOVE,02 - ADULT,09/02/2022,01/10/2023,7,40,2,10,Si,Sí
8134,421633,"BECHI , MARINA LORENA",Mujer,39,BARCELONA,BARCELONA,08018,"CARRER CLOT, 126 3º 4ª",VINTRO FAMILIAR,02 - ADULT,08/09/2022,01/07/2023,37,27,9,7,No,Sí
8135,421683,"GARRIDO LEPE, MARTIN",Hombre,37,barcelona,Basrcelona,08018,"CARRER SANT JOAN DE MALTA,",VINTRO COMPLERT,02 - ADULT,29/11/2022,01/01/2023,49,1,11,1,No,Sí

In [5]:
d= d[d['Edad'] != '(nulo)']

In [6]:
x = d['Edad'].value_counts().head(10)

In [7]:
def plot_bar(sort_by="Index"):
    if sort_by == "Index":
        sorted_counts = x.sort_index()
    elif sort_by == "Frequency Asc":
        sorted_counts = x.sort_values(ascending=True)
    else:  # Frequency Desc
        sorted_counts = x.sort_values(ascending=False)
    
    plt.figure(figsize=(8, 5))
    plt.bar(sorted_counts.index, sorted_counts.values, color='skyblue', alpha=0.7, edgecolor='k')
    plt.title("Interactive Bar Plot")
    plt.xlabel("Category")
    plt.ylabel("Frequency")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

In [9]:
interact(plot_bar, sort_by=["Index", "Frequency Asc", "Frequency Desc"])

interactive(children=(Dropdown(description='sort_by', options=('Index', 'Frequency Asc', 'Frequency Desc'), va…

In [16]:
def gender_barplot(min_age, max_age):
    # Filter data based on age range
    filtered_df = d[(d["Edad"].astype(int) >= min_age) & (d["Edad"].astype(int) <= max_age)]
    
    # Count gender occurrences
    gender_counts = filtered_df["Sexo"].value_counts()
    
    # Create a barplot

    plt.figure(figsize=(8, 5))
    plt.bar(gender_counts.index, gender_counts.values, color='skyblue', alpha=0.7, edgecolor='k')
    plt.title("Gráfico de género en intervalo de edad")
    plt.xlabel("Category")
    plt.ylabel("Cantidad")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

In [18]:
interact(
  
    gender_barplot,
    min_age=IntSlider(value=18, min=20, max=60, step=1, description="Edad Mínima"),
    max_age=IntSlider(value=60, min=20, max=60, step=1, description="Edad Máxima")
    
)

interactive(children=(IntSlider(value=20, description='Edad Mínima', max=60, min=20), IntSlider(value=60, desc…